language: node_js
node_js:
  - 10
branches:
  only:
    - master
install:
  - npm install
script:
  - npm test
after_success:
  - npm run test:cov -- --report lcovonly && cat ./coverage/lcov.info | coveralls
